### ISSUE TITLE
update website with logo

### ISSUE THREAD

**Issue by abbyjerger** [pnnl-predictive-phenomics/clean-contact#11]
Can we get the website updated with EMSL's logo? I believe @cbrasfield already made the code changes, I think to the cc-1 branch, but they need to be deployed.

For example, this website: https://ersa.guans.cs.kent.edu/ should include the EMSL logo at the bottom of the page like the mockup does: http://meowlecule.com/clean-contact/

Please and thank you!

**Comment by yuxin212** [comment]
Thanks for letting me know! I have added the ESML logo to [the website](https://ersa.guans.cs.kent.edu). 
We previously used the website code from the webstyling-update branch where the EMSL logo was not included.
