### ISSUE TITLE
check data processing notebook

### ISSUE THREAD

**Issue by abbyjerger** [pnnl-predictive-phenomics/clean-contact#7]
The data processing jupyter notebook can be found here: https://github.com/pnnl-predictive-phenomics/clean-contact/blob/2-case-study/case-study/analysis/notebooks/data_processing.ipynb

- [x] in one of the cells, in a comment, I included the BioCyc link you gave me with the MED4 data. Is there any reason that we should not include that link?
- [x] can you please check the BioCyc markdown section of the notebook, near the bottom, for accurate info about BioCyc?

**Comment by djinnome** [comment]
- [x] No reason not to include the link
- [x] The duplicate Uniprot id problem has been fixed by the BioCyc folks.  Otherwise, it looks accurate.

**Comment by abbyjerger** [comment]
Updated that info in the notebook- thank you!

**Comment by djinnome** [comment]
Oh, wait. There is a reason not to use the link I gave you:  It is behind a paywall.  Let me see if I can add MED4 to cyc.pnnl.gov so that reviewers can see it.
